server:
  port: 8080
spring:
  activiti:
    check-process-definitions: false
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: LEGACYHTML5
  datasource:
    url: jdbc:mysql://localhost:3306/mtg?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT&useSSL=false
    username: root
    password: root@123
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
